### ISSUE TITLE
Filter out replies from twitter posts

### ISSUE THREAD

**Issue by jschr** [jschr/jschr.io#11]
Only show tweets and retweets, not replies.

**Comment by Sylk** [comment]
Updates?

**Comment by jschr** [comment]
hey @Sylk, I decided not to do this because I don't tweet much anyways. This should be as easy as filtering out tweets with a reply id in [getProps](app.getProps.ts):

```js
function getTwitterSummary(username: string, timeline: twitter.Timeline): Summary {
  const latestTweet = timeline.find(tweet => !tweet.in_reply_to_status_id)

  return {
    text: ellipsize(stripHtml(latestTweet.text), TEXT_LENGTH),
    href: `https://twitter.com/@${username}/status/${latestTweet.id_str}`,
    createdAt: new Date(latestTweet.created_at)
  }
}
```

Let me know if you have any other questions / feedback. If you're deploying your own version I'd love to check it out!
