### ISSUE TITLE
screw_ie8 is not assignable to type 'boolean'

### ISSUE THREAD

**Issue by qonl** [jschr/jschr.io#16]
Hello, found your site on reddit and saw there was a tutorial for it on your github. I've recently become interested in Serverless architecture and decided to try to use your code to create my own. Upon setting all the env variables and running `yarn start` I get this error:

`TSError: ⨯ Unable to compile TypeScript
app/webpack.config.ts (77,15): Argument of type '{ compress: { screw_ie8: boolean; }; }' is not assignable to parameter of type 'Options'.
  Types of property 'compress' are incompatible.
    Type '{ screw_ie8: boolean; }' is not assignable to type 'boolean | CompressOptions'.
      Object literal may only specify known properties, and 'screw_ie8' does not exist in type 'boolean | CompressOptions'. (2345)
    at getOutput (/Users/quintenoneal/Desktop/jschr.io-master/node_modules/ts-node/src/index.ts:307:15)
    at /Users/quintenoneal/Desktop/jschr.io-master/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/Users/quintenoneal/Desktop/jschr.io-master/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/Users/quintenoneal/Desktop/jschr.io-master/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/quintenoneal/Desktop/jschr.io-master/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)`

When I remove the screw_ie8 line in webpack config I get a status code 400 when running the command. Any idea what could be the issue?

**Comment by jschr** [comment]
Hey, sounds like you've got an incompatible version of webpack installed. Peaking into the `yarn.lock` shows I had webpack `2.2.14` installed. Could you try installing that exact version if it isn't already? 

Looks like `screw_ie8` was renamed to `ie` so you could also try replacing the config with `ie: false` instead: https://github.com/gruntjs/grunt-contrib-uglify/issues/40#issuecomment-358585176

Could you elaborate more on where the 400 is coming from? When you run `yarn start` it fetches data from twitter, medium, etc.. here: https://github.com/jschr/jschr.io/blob/master/app/webpack.config.ts#L11

Do you have the env vars setup? Checkout the README if not.

I haven't updated this project in a while but I'm planning on doing that soon, it will follow the same architecture.

In the meantime, happy to help you get this up an running. Let me know if anything needs clarification.

**Comment by jschr** [comment]
You may also be interested in a more recent project: https://github.com/jschr/vscodethemes

It's a serverless web scrapper using Lambda, SQS and SNS. I also setup continuous deployment with Terraform. Part of the update to this project will be pulling in things I learned from there.

**Comment by qonl** [comment]
Thanks for getting back!

Unfortunately changing the screw_ie8: true to ie: false did nothing, also tried changing to true. what did work though was reverting back to that version of webpack. 

Now my issue are three @type errors with webpack.

`ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:556:28 
    TS2507: Type 'typeof import("/Users/quintenoneal/Desktop/jschr.io-master/node_modules/@types/tapable/index")' is not a constructor function type.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:598:46 
    TS2694: Namespace '"/Users/quintenoneal/Desktop/jschr.io-master/node_modules/@types/tapable/index"' has no exported member 'Plugin'.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:602:53 
    TS2694: Namespace '"/Users/quintenoneal/Desktop/jschr.io-master/node_modules/@types/tapable/index"' has no exported member 'Plugin'.
webpack: Failed to compile.`

I deleted the @type/react components that yarn added, because for some reason it was not installing the same versions for the two. So a simple `npm install` fixed that. Now all that shows are those errors, but the site works.

**Comment by jschr** [comment]
Hmm.. doesn't look like `@types/tapable` is used so try deleting it. It's possible I removed it from package.json manually (instead of `yarn remove`) so it's left over in the yarn.lock file.

**Comment by qonl** [comment]
Removed tapable and it compiled successfully. Thank you!
